export const CREATE_TODO = 'CREATE_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const CHANGE_TODO_LABEL = 'CHANGE_TODO_LABEL';
export const CHANGE_TODO_COMPLETED = 'CHANGE_TODO_COMPLETED';
export const CHANGE_ALL_TODOS_COMPLETED = 'CHANGE_ALL_TODOS_COMPLETED';
export const REMOVE_COMPLETED_TODOS = 'REMOVE_COMPLETED_TODOS';
export const CHANGE_FILTER = 'CHANGE_FILTER';
